services:
  postgres:
    image: postgres:17
    container_name: ciber_ciudadanos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ciber_ciudadanos_db
      POSTGRES_USER: ciber_ciudadanos_user
      POSTGRES_PASSWORD: ciber_ciudadanos_pass 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

